// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ByebyeController from "./byebye_controller"
application.register("byebye", ByebyeController)

import CardsController from "./cards_controller"
application.register("cards", CardsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShowBookingsController from "./show_bookings_controller"
application.register("show-bookings", ShowBookingsController)

import TypedController from "./typed_controller"
application.register("typed", TypedController)

import AllCheckboxesController from "./all_checkboxes_controller"
application.register("all-checkboxes", AllCheckboxesController)
